name: Extension Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Extension
      run: |
        mkdir -p dist/chrome dist/firefox
        cp -r src/* dist/
        
        # Prepare Chrome extension
        zip -r dist/chrome/animestars_extension-${{ github.ref_name }}-chrome.zip dist/
        
        # Prepare Firefox extension
        zip -r dist/firefox/animestars_extension-${{ github.ref_name }}-firefox.xpi dist/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/chrome/animestars_extension-${{ github.ref_name }}-chrome.zip
          dist/firefox/animestars_extension-${{ github.ref_name }}-firefox.xpi
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Manifest Versions
      run: |
        # Update Chrome manifest
        sed -i 's/"version": "[^"]*"/"version": "${{ github.ref_name }}"/' src/manifest/manifest.chrome.json
        
        # Update Firefox manifest
        sed -i 's/"version": "[^"]*"/"version": "${{ github.ref_name }}"/' src/manifest/manifest.firefox.json
    
    - name: Commit Version Updates
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add src/manifest/manifest.chrome.json src/manifest/manifest.firefox.json
        git commit -m "Update manifest versions to ${{ github.ref_name }}"
        git push 